# Generated by Django 3.1.4 on 2020-12-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='mtext',
            field=models.JSONField(blank=True, max_length=255),
        ),
    ]
