# Generated by Django 3.1.4 on 2020-12-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0002_auto_20201229_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='state',
        ),
    ]
