# Generated by Django 3.1.4 on 2020-12-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0003_remove_user_info_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
