# Generated by Django 3.1.4 on 2020-12-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0004_user_info_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='qtag',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
