# Generated by Django 3.1.4 on 2020-12-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0005_user_info_qtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='ans',
            field=models.JSONField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='mtext',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
