# Generated by Django 3.1.4 on 2021-01-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0009_user_info_qtag_deep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='qtag_deep',
            new_name='qdeep',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='ans',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
