# Generated by Django 3.1.4 on 2021-01-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0010_auto_20210110_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='qdeep',
            new_name='qtag2',
        ),
    ]
