# Generated by Django 3.1.4 on 2021-01-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0011_auto_20210110_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='qtag',
        ),
        migrations.AddField(
            model_name='user_info',
            name='qname',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
