# Generated by Django 3.1.4 on 2021-01-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0012_auto_20210119_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='qtag2',
        ),
        migrations.AddField(
            model_name='user_info',
            name='hos',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_info',
            name='qnaire',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_info',
            name='qtag',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='qname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
