# Generated by Django 3.1.4 on 2021-01-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0013_auto_20210119_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='hos',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='qnaire',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='qname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
