# -*- coding: utf-8 -*-
"""
Created on Wed Dec 23 16:07:08 2020

@author: Alan Lin
"""

#這些是LINE官方開放的套件組合透過import來套用這個檔案上
from django.conf import settings
from linebot import (LineBotApi, WebhookHandler)
from linebot.exceptions import (InvalidSignatureError)
from linebot.models import *
line_bot_api = LineBotApi(settings.LINE_CHANNEL_ACCESS_TOKEN)
# Questionnaire(問卷)
    
def questionhos():
    message=TextSendMessage(
    text="就診醫院",
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label="ShuangHo",text="ShuangHo")
                ),
            QuickReplyButton(
                action=MessageAction(label="TMUH",text="TMUH")
                ),
            QuickReplyButton(
                action=MessageAction(label="Wanfang",text="Wanfang")
                )
            ]
        )
    ) 
    return message

def questionnaire():
    message=TextSendMessage(
    text="問卷類別",
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label="First",text="First")
                ),
            QuickReplyButton(
                action=MessageAction(label="TwoWeeks",text="TwoWeeks")
                ),
            QuickReplyButton(
                action=MessageAction(label="PerMonth",text="PerMonth")
                )
            ]
        )
    )
    return message
    
def topic_1(reply_token,Q,A1):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)

def topic_2(reply_token,Q,A1,A2):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)

def topic_3(reply_token,Q,A1,A2,A3):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                )            
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)

def topic_4(reply_token,Q,A1,A2,A3,A4):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)

def topic_5(reply_token,Q,A1,A2,A3,A4,A5):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)

def topic_6(reply_token,Q,A1,A2,A3,A4,A5,A6):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)
    
def topic_7(reply_token,Q,A1,A2,A3,A4,A5,A6,A7):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)
    
def topic_8(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)

def topic_9(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)

def topic_10(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)

def topic_11(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                ),
            QuickReplyButton(
                action=MessageAction(label=A11,text='10')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)

def topic_12(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                ),
            QuickReplyButton(
                action=MessageAction(label=A11,text='10')
                ),
            QuickReplyButton(
                action=MessageAction(label=A12,text='11')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)

def topic_13(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                ),
            QuickReplyButton(
                action=MessageAction(label=A11,text='10')
                ),
            QuickReplyButton(
                action=MessageAction(label=A12,text='11')
                ),
            QuickReplyButton(
                action=MessageAction(label=A13,text='12')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)
    
def topic_14(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                ),
            QuickReplyButton(
                action=MessageAction(label=A11,text='10')
                ),
            QuickReplyButton(
                action=MessageAction(label=A12,text='11')
                ),
            QuickReplyButton(
                action=MessageAction(label=A13,text='12')
                ),
            QuickReplyButton(
                action=MessageAction(label=A14,text='13')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)
    
def topic_15(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                ),
            QuickReplyButton(
                action=MessageAction(label=A11,text='10')
                ),
            QuickReplyButton(
                action=MessageAction(label=A12,text='11')
                ),
            QuickReplyButton(
                action=MessageAction(label=A13,text='12')
                ),
            QuickReplyButton(
                action=MessageAction(label=A14,text='13')
                ),
            QuickReplyButton(
                action=MessageAction(label=A15,text='14')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)
    
def topic_16(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                ),
            QuickReplyButton(
                action=MessageAction(label=A11,text='10')
                ),
            QuickReplyButton(
                action=MessageAction(label=A12,text='11')
                ),
            QuickReplyButton(
                action=MessageAction(label=A13,text='12')
                ),
            QuickReplyButton(
                action=MessageAction(label=A14,text='13')
                ),
            QuickReplyButton(
                action=MessageAction(label=A15,text='14')
                ),
            QuickReplyButton(
                action=MessageAction(label=A16,text='15')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)
    
def topic_17(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16,A17):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                ),
            QuickReplyButton(
                action=MessageAction(label=A11,text='10')
                ),
            QuickReplyButton(
                action=MessageAction(label=A12,text='11')
                ),
            QuickReplyButton(
                action=MessageAction(label=A13,text='12')
                ),
            QuickReplyButton(
                action=MessageAction(label=A14,text='13')
                ),
            QuickReplyButton(
                action=MessageAction(label=A15,text='14')
                ),
            QuickReplyButton(
                action=MessageAction(label=A16,text='15')
                ),
            QuickReplyButton(
                action=MessageAction(label=A17,text='16')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)
    
def topic_18(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16,A17,A18):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                ),
            QuickReplyButton(
                action=MessageAction(label=A11,text='10')
                ),
            QuickReplyButton(
                action=MessageAction(label=A12,text='11')
                ),
            QuickReplyButton(
                action=MessageAction(label=A13,text='12')
                ),
            QuickReplyButton(
                action=MessageAction(label=A14,text='13')
                ),
            QuickReplyButton(
                action=MessageAction(label=A15,text='14')
                ),
            QuickReplyButton(
                action=MessageAction(label=A16,text='15')
                ),
            QuickReplyButton(
                action=MessageAction(label=A17,text='16')
                ),
            QuickReplyButton(
                action=MessageAction(label=A18,text='17')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)
    
def topic_19(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16,A17,A18,A19):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                ),
            QuickReplyButton(
                action=MessageAction(label=A11,text='10')
                ),
            QuickReplyButton(
                action=MessageAction(label=A12,text='11')
                ),
            QuickReplyButton(
                action=MessageAction(label=A13,text='12')
                ),
            QuickReplyButton(
                action=MessageAction(label=A14,text='13')
                ),
            QuickReplyButton(
                action=MessageAction(label=A15,text='14')
                ),
            QuickReplyButton(
                action=MessageAction(label=A16,text='15')
                ),
            QuickReplyButton(
                action=MessageAction(label=A17,text='16')
                ),
            QuickReplyButton(
                action=MessageAction(label=A18,text='17')
                ),
            QuickReplyButton(
                action=MessageAction(label=A19,text='18')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)
    
def topic_20(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16,A17,A18,A19,A20):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                ),
            QuickReplyButton(
                action=MessageAction(label=A11,text='10')
                ),
            QuickReplyButton(
                action=MessageAction(label=A12,text='11')
                ),
            QuickReplyButton(
                action=MessageAction(label=A13,text='12')
                ),
            QuickReplyButton(
                action=MessageAction(label=A14,text='13')
                ),
            QuickReplyButton(
                action=MessageAction(label=A15,text='14')
                ),
            QuickReplyButton(
                action=MessageAction(label=A16,text='15')
                ),
            QuickReplyButton(
                action=MessageAction(label=A17,text='16')
                ),
            QuickReplyButton(
                action=MessageAction(label=A18,text='17')
                ),
            QuickReplyButton(
                action=MessageAction(label=A19,text='18')
                ),
            QuickReplyButton(
                action=MessageAction(label=A20,text='19')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)

def topic_21(reply_token,Q,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16,A17,A18,A19,A20,A21):
    message=TextSendMessage(
    text=Q,
    quick_reply=QuickReply(
        items=[
            QuickReplyButton(
                action=MessageAction(label=A1,text='0')
                ),
            QuickReplyButton(
                action=MessageAction(label=A2,text='1')
                ),
            QuickReplyButton(
                action=MessageAction(label=A3,text='2')
                ),
            QuickReplyButton(
                action=MessageAction(label=A4,text='3')
                ),
            QuickReplyButton(
                action=MessageAction(label=A5,text='4')
                ),
            QuickReplyButton(
                action=MessageAction(label=A6,text='5')
                ),
            QuickReplyButton(
                action=MessageAction(label=A7,text='6')
                ),
            QuickReplyButton(
                action=MessageAction(label=A8,text='7')
                ),
            QuickReplyButton(
                action=MessageAction(label=A9,text='8')
                ),
            QuickReplyButton(
                action=MessageAction(label=A10,text='9')
                ),
            QuickReplyButton(
                action=MessageAction(label=A11,text='10')
                ),
            QuickReplyButton(
                action=MessageAction(label=A12,text='11')
                ),
            QuickReplyButton(
                action=MessageAction(label=A13,text='12')
                ),
            QuickReplyButton(
                action=MessageAction(label=A14,text='13')
                ),
            QuickReplyButton(
                action=MessageAction(label=A15,text='14')
                ),
            QuickReplyButton(
                action=MessageAction(label=A16,text='15')
                ),
            QuickReplyButton(
                action=MessageAction(label=A17,text='16')
                ),
            QuickReplyButton(
                action=MessageAction(label=A18,text='17')
                ),
            QuickReplyButton(
                action=MessageAction(label=A19,text='18')
                ),
            QuickReplyButton(
                action=MessageAction(label=A20,text='19')
                ),
            QuickReplyButton(
                action=MessageAction(label=A21,text='20')
                )
            ]
        )
    )
    line_bot_api.reply_message(reply_token,message)







